FROM ghcr.io/pyrethrum/webdriver-precore:latest


# vscode user created in haskell
ENV DEBIAN_FRONTEND=noninteractive \
  USERNAME=vscode \
  # modified from https://github.com/vzarytovskii/haskell-dev-env/blob/master/.devcontainer/Dockerfile 
  # this 1000 is aready taken by ubuntu
  USER_UID=1001 \
  USER_GID=1001
  
  # ensure switched user
  USER ${USER_UID}:${USER_GID}
  
  # Set the working directory
  WORKDIR /home/vscode

# Install Firefox by running the install script
COPY install-firefox.sh /home/vscode/install-firefox.sh

USER root
RUN echo "Install firefox" && \
    chown ${USER_UID}:${USER_GID} /home/vscode/install-firefox.sh && \
    ls -l /home/vscode/install-firefox.sh && \
    chmod +x /home/vscode/install-firefox.sh && \
    /home/vscode/install-firefox.sh && \
    rm /home/vscode/install-firefox.sh
USER ${USER_UID}:${USER_GID}

# Install geckodriver by running the install script
COPY install-gecko-driver.sh /home/vscode/install-gecko-driver.sh
USER root
RUN echo "Install geckodriver" && \
    chmod +x /home/vscode/install-gecko-driver.sh && \
    /home/vscode/install-gecko-driver.sh && \ 
    rm /home/vscode/install-gecko-driver.sh
USER ${USER_UID}:${USER_GID}

# Specify the default command to run when the container starts
CMD ["bash"]