ARG BUILD_IMAGE=webdriver-build
FROM ${BUILD_IMAGE}

RUN apt-get update && apt-get install -y --fix-missing \
    wget \
    libgtk-3-0 \
    libdbus-glib-1-2 \
    libasound2 \
    libx11-xcb1 \
    libxt6 \
    libpci3

RUN wget -O firefox.tar.xz \
    "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US" \
    && tar -xJf firefox.tar.xz -C /opt \
    && ln -s /opt/firefox/firefox /usr/local/bin/firefox

RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz | tar xz -C /usr/local/bin

ENV DEBIAN_FRONTEND=noninteractive
ENV MOZ_HEADLESS=1
RUN geckodriver &
RUN cabal test all -j
