cabal-version: 3.12

name:           webdriver-precore
version:        0.2.0.2
homepage:       https://github.com/pyrethrum/webdriver-precore#readme
bug-reports:    https://github.com/pyrethrum/webdriver-precore/issues
author:         John Walker, Adrian Glouftsis
maintainer:     theghostjw@gmail.com
category:       Webb, WebDriver, Testing
copyright:      2025 John Walker, Adrian Glouftsis
license:        BSD-3-Clause
license-file:   LICENSE
build-type:     Simple

extra-doc-files: 
  README.md
  ChangeLog.md

tested-with: GHC == 9.8.2 || == 9.8.4 || == 9.10.1

synopsis:       A typed wrapper for W3C WebDriver (HTTP and BiDi) protocols.

description:
  This library provides typed definitions for the WebDriver W3C spec, both @<https://www.w3.org/TR/2025/WD-webdriver2-20251028/ HTTP>@ and @<https://www.w3.org/TR/2026/WD-webdriver-bidi-20260109/ BiDi>@.

  It is designed as a foundation for building WebDriver client libraries providing type-safe endpoint definitions and response parsers without any client implementation.

  If you are looking for a fully implemented web client library, you should check out an alternative such as [haskell-webdriver](https://github.com/haskell-webdriver/haskell-webdriver#readme).

  __For complete documentation, module organisation, and migration guides, see "WebDriverPreCore".__
  
  See also the @<https://github.com/pyrethrum/webdriver project repo>@ and the test directory for @<https://github.com/pyrethrum/webdriver/tree/main/webdriver-precore/test#readme examples>@.
  
common commonExtensions
  default-extensions:
    AllowAmbiguousTypes
      BangPatterns
      BlockArguments
      ConstrainedClassMethods
      ConstraintKinds
      DisambiguateRecordFields
      DuplicateRecordFields
      DataKinds
      DefaultSignatures
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveLift
      DeriveTraversable
      DerivingStrategies
      EmptyCase
      ExistentialQuantification
      ExtendedDefaultRules
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      GeneralizedNewtypeDeriving
      ImportQualifiedPost
      InstanceSigs
      KindSignatures
      LambdaCase
      LiberalTypeSynonyms
      MultiParamTypeClasses
      MultiWayIf
      NamedFieldPuns
      NoFieldSelectors
      NumericUnderscores
      OverloadedStrings
      OverloadedRecordDot
      PartialTypeSignatures
      PatternSynonyms
      PolyKinds
      QuasiQuotes
      RankNTypes
      RecordWildCards
      ScopedTypeVariables
      StandaloneDeriving
      StrictData
      TemplateHaskell
      TupleSections
      TypeApplications
      TypeFamilies
      TypeFamilyDependencies
      TypeOperators

flag debug-local-config
  description: Use local debug configuration (ignore Dhall file in test/.config)
  default: False
  manual: True

common commonGhcOptions
  ghc-options:
    -fmax-pmcheck-models=10000000 
    -ferror-spans 
    -fprint-potential-instances 
    -Wall 
    -Wcompat 
    -Wincomplete-record-updates 
    -Wincomplete-uni-patterns 
    -Wredundant-constraints
    -fwarn-tabs 
    -fwrite-ide-info 
    -fno-warn-type-defaults 
    -fno-warn-unused-do-bind 
    -Wno-overlapping-patterns 
    -Wno-deprecations
    -fbyte-code-and-object-code 
    -- -fdefer-type-errors

  cpp-options: 
    -DHTMLSpecURL=https://www.w3.org/TR/2025/WD-webdriver2-20251028/
    -DBiDiSpecURL=https://www.w3.org/TR/2026/WD-webdriver-bidi-20260109/

  if flag(debug-local-config)
    cpp-options: -DDEBUG_LOCAL_CONFIG

common testDepends
  build-depends:
    aeson         >=1.4   && <2.3,
    base          >=4.16  && <5,
    tasty         >=1.4   && <1.6,
    tasty-hunit   >=0.10  && <0.11,
    text          >=2.1   && <2.2

flag legacy-test
  description: Use legacy deprecated HTTP test implementations
  default: False
  manual: True

library utils-internal
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      AesonUtils
      Utils
      WebDriverPreCore.Error
      WebDriverPreCore.HTTP.Command
      WebDriverPreCore.Utils.Timeout
  hs-source-dirs: utils
  build-depends:
    base          >=4.16  && <5,
    aeson         >=1.4   && <2.3,
    aeson-pretty  >=0.8   && <0.9,
    bytestring    >=0.10  && <0.12.3,
    text          >=2.1   && <2.2,
    containers    >=0.6   && <0.9,
    pretty-show ^>=1.10
  default-language: Haskell2010

test-suite test-utils
  import: commonExtensions, commonGhcOptions
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: utils/test
  build-depends:
    webdriver-precore:utils-internal,
    base,
    tasty,
    tasty-hunit
  default-language: Haskell2010

library webdriver-precore-test-resources
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriverPreCore.TestResources
  hs-source-dirs: test-resources/src
  build-depends:
    base          >=4.16  && <5,
    bytestring    >=0.10  && <0.12.3,
    file-embed    >=0.0.15 && <0.1,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

library webdriver-precore-test-utils
  import: commonExtensions, commonGhcOptions
  exposed-modules: 
      WebDriverPreCore.Test.Config
      WebDriverPreCore.Test.ConfigLoader
      WebDriverPreCore.Test.Const
      WebDriverPreCore.Test.ExpectedErrors
      WebDriverPreCore.Test.IOUtils
      WebDriverPreCore.Test.Logger
      WebDriverPreCore.Test.CapabilitiesBuilder
      WebDriverPreCore.Test.TestData
      WebDriverPreCore.Test.TestServerAPI

  if flag(debug-local-config)
    exposed-modules:
      WebDriverPreCore.Test.DebugConfig
      
  hs-source-dirs: test-utils/src
  build-depends:
    webdriver-precore:utils-internal,
    webdriver-precore:webdriver-precore,
    aeson         >=1.4   && <2.3,
    base          >=4.16  && <5,
    base64        >=0.4   && <1.1,
    bytestring    >=0.10  && <0.12.3,
    dhall         >=1.40  && <1.43,
    directory     >=1.3   && <1.4,
    filepath      >=1.5   && <1.6,
    req           >=3.9   && <3.14,
    tasty-hunit   >=0.10  && <0.11,
    text          >=2.1   && <2.2,
    time          >=1.9   && <1.15,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

library webdriver-precore-http-runner
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriverPreCore.HttpRunner
      WebDriverPreCore.HttpRunner.Utils
  hs-source-dirs: http-runner/src
  build-depends:
    webdriver-precore:utils-internal,
    aeson         >=1.4   && <2.3,
    base          >=4.16  && <5,
    bytestring    >=0.10  && <0.12.3,
    req           >=3.9   && <3.14,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

test-suite test-http-runner
  import: commonExtensions, commonGhcOptions
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: http-runner/test
  -- TODO: restore legacy files when flag is enabled
  -- see main
  if flag(legacy-test)
    cpp-options: -DLEGACY_TEST
  other-modules:
    Actions
    ErrorDemo
    FallbackDemo
    HttpDemo
    HttpDemoUtils
  build-depends:
    webdriver-precore:utils-internal,
    webdriver-precore:webdriver-precore,
    webdriver-precore:webdriver-precore-http-runner,
    webdriver-precore:webdriver-precore-test-resources,
    webdriver-precore:webdriver-precore-test-utils,
    aeson,
    base,
    bytestring,
    containers,
    dhall,
    req,
    tasty,
    tasty-hunit,
    text,
    time,
    unliftio
  default-language: Haskell2010

library webdriver-precore-bidi-runner-base
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriverPreCore.BiDiRunnerBase
      WebDriverPreCore.BiDiRunnerBase.Socket
      WebDriverPreCore.BiDiRunnerBase.Response
      WebDriverPreCore.BiDiRunnerBase.Types
  hs-source-dirs: bidi-runner-base/src
  build-depends:
    aeson         >=1.4   && <2.3,
    aeson-pretty  >=0.8   && <0.9,
    base          >=4.16  && <5,
    bytestring    >=0.10  && <0.12.3,
    containers    >=0.6   && <0.9,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3,
    websockets    >=0.12  && <0.14
  default-language: Haskell2010

test-suite test-bidi-runner-base
  import: commonExtensions, commonGhcOptions, testDepends
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: bidi-runner-base/test
  build-depends:
    webdriver-precore:webdriver-precore-bidi-runner-base
  default-language: Haskell2010

library webdriver-precore-bidi-runner
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriverPreCore.BiDiRunner
  hs-source-dirs: bidi-runner/src
  build-depends:
    webdriver-precore:webdriver-precore,
    webdriver-precore:webdriver-precore-bidi-runner-base,
    aeson         >=1.4   && <2.3,
    base          >=4.16  && <5,
    containers    >=0.6   && <0.9,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

test-suite test-bidi-runner
  import: commonExtensions, commonGhcOptions
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: bidi-runner/test
  other-modules:
    Actions
    BiDiDemoUtils
    BrowserDemos
    BrowsingContextDemos
    BrowsingContextEventDemos
    EmulationDemos
    ErrorDemo
    FallbackDemos
    HttpActions
    InputDemos
    InputEventDemos
    LogEventDemos
    NetworkDemos
    NetworkEventDemos
    NetworkSupportTest
    OtherDemos
    ScriptDemos
    ScriptEventDemos
    SessionDemos
    StorageDemos
    WebExtensionDemos
  build-depends:
    webdriver-precore:utils-internal,
    webdriver-precore:webdriver-precore,
    webdriver-precore:webdriver-precore-bidi-runner,
    webdriver-precore:webdriver-precore-bidi-runner-base,
    webdriver-precore:webdriver-precore-http-runner,
    webdriver-precore:webdriver-precore-test-resources,
    webdriver-precore:webdriver-precore-test-utils,
    aeson,
    base,
    bytestring,
    containers,
    dhall,
    tasty,
    tasty-hunit,
    text,
    time,
    unliftio,
    websockets
  default-language: Haskell2010

library webdriver-precore-extended
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriverPreCore.Extended
      WebDriverPreCore.Extended.Capabilities
      WebDriverPreCore.Extended.HTTP.Base.API
      WebDriverPreCore.Extended.HTTP.Base.Protocol
      WebDriverPreCore.Extended.HTTP.Base.Actions
      WebDriverPreCore.Extended.BiDi.Base.API
      WebDriverPreCore.Extended.BiDi.Base.Protocol
      WebDriverPreCore.Extended.BiDi.Base.Actions
  hs-source-dirs: extended/src
  build-depends:
    webdriver-precore:webdriver-precore,
    webdriver-precore:utils-internal,
    aeson         >=1.4   && <2.3, 
    base          >=4.16  && <5,
    containers    >=0.6   && <0.8,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

test-suite test-extended
  import: commonExtensions, commonGhcOptions, testDepends
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: extended/test
  build-depends:
    webdriver-precore:webdriver-precore-extended
  default-language: Haskell2010

library webdriver-precore-driver-control
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriverPreCore.DriverControl
  hs-source-dirs: driver-control/src
  build-depends:
    base          >=4.16  && <5,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3,
    typed-process >=0.2   && <0.3,
    path          >=0.9   && <0.10,
    path-io       >=1.8   && <1.9
  default-language: Haskell2010

test-suite test-driver-control
  import: commonExtensions, commonGhcOptions, testDepends
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: driver-control/test
  build-depends:
    webdriver-precore:webdriver-precore-driver-control
  default-language: Haskell2010

library webdriver-effectful
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriver.Effectful
  hs-source-dirs: effectful/src
  build-depends:
    webdriver-precore:webdriver-precore-extended,
    base          >=4.16  && <5,
    effectful     >=2.3   && <2.7,
    effectful-core >=2.3  && <2.7,
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

test-suite test-effectful
  import: commonExtensions, commonGhcOptions, testDepends
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: effectful/test
  build-depends:
    webdriver-precore:webdriver-effectful
  default-language: Haskell2010

library webdriver-rio-poc
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriver.RIO
      WebDriver.RIO.App
      WebDriver.RIO.BiDi.Base
      WebDriver.RIO.Env
      WebDriver.RIO.HTTP.Base
      WebDriver.RIO.HTTP.Base.Actions
      WebDriver.RIO.Logging
  hs-source-dirs: rio-poc/src
  build-depends:
    webdriver-precore:webdriver-precore,
    webdriver-precore:webdriver-precore-extended,
    webdriver-precore:webdriver-precore-http-runner,
    webdriver-precore:webdriver-precore-bidi-runner,
    webdriver-precore:utils-internal,
    aeson         >=2.0   && <3,
    base          >=4.16  && <5,
    rio           >=0.1   && <0.2
  default-language: Haskell2010

test-suite test-rio-poc
  import: commonExtensions, commonGhcOptions, testDepends
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: rio-poc/test
  build-depends:
    webdriver-precore:webdriver-precore-extended,
    webdriver-precore:webdriver-precore-test-utils,
    webdriver-precore:webdriver-rio-poc,
    webdriver-precore:utils-internal,
    rio           >=0.1   && <0.2
  default-language: Haskell2010

library webdriver-bluefin-poc
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      WebDriver.Bluefin
  hs-source-dirs: bluefin-poc/src
  build-depends:
    webdriver-precore:webdriver-precore-extended,
    base          >=4.16  && <5,
    bluefin       >=0.2   && <0.5, 
    text          >=2.1   && <2.2,
    unliftio      >=0.2   && <0.3
  default-language: Haskell2010

test-suite test-bluefin-poc
  import: commonExtensions, commonGhcOptions, testDepends
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: bluefin-poc/test
  build-depends:
    webdriver-precore:webdriver-bluefin-poc
  default-language: Haskell2010

library
  import: commonExtensions, commonGhcOptions
  exposed-modules:
      -- Main documentation module
      WebDriverPreCore
      -- BiDi
      WebDriverPreCore.BiDi.API
      WebDriverPreCore.BiDi.Protocol
      -- HTTP
      WebDriverPreCore.HTTP.API
      WebDriverPreCore.HTTP.Protocol
      -- Deprecated (to be removed ~ 2027-02-01)
      WebDriverPreCore.Http
      WebDriverPreCore.HTTP.SpecDefinition
      WebDriverPreCore.HTTP.HttpResponse
  other-modules:
      -- Shared
      WebDriverPreCore.Internal.HTTPBidiCommon
      -- HTTP
      WebDriverPreCore.HTTP.Capabilities
      -- BiDI
      WebDriverPreCore.BiDi.Browser
      WebDriverPreCore.BiDi.BrowsingContext
      WebDriverPreCore.BiDi.Capabilities
      WebDriverPreCore.BiDi.Command
      WebDriverPreCore.BiDi.CoreTypes
      WebDriverPreCore.BiDi.Emulation
      WebDriverPreCore.BiDi.Event
      WebDriverPreCore.BiDi.Log
      WebDriverPreCore.BiDi.Input
      WebDriverPreCore.BiDi.Network
      WebDriverPreCore.BiDi.Script
      WebDriverPreCore.BiDi.Session
      WebDriverPreCore.BiDi.Storage
      WebDriverPreCore.BiDi.WebExtensions
  hs-source-dirs: src
  build-depends:
    webdriver-precore:utils-internal,
    aeson         >=1.4   && <2.3, 
    base          >=4.16  && <5,
    bytestring    >=0.10  && <0.12.3,
    text          >=2.1   && <2.2,
    containers    >=0.6   && <0.9,
    vector        >=0.12  && <0.14
  default-language: Haskell2010

test-suite test
  import: commonExtensions, commonGhcOptions
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: test
  build-depends:
    aeson
    , webdriver-precore:utils-internal
    , base
    , base64
    , bytestring
    , containers
    , dhall
    , directory >=1.3 && <1.4
    , falsify
    , filepath
    , ghc
    , network
    , pretty-show ^>=1.10
    , raw-strings-qq
    , req
    , tasty
    , tasty-hunit
    , time
    , text
    , unliftio
    , webdriver-precore:webdriver-precore
    , websockets
  other-modules:
   -- true unit/property tests
    ApiCoverageTest
    , ErrorCoverageTest
    , JSONParsingTest
  default-language: Haskell2010
