{-|
BiDi Actions module for webdriver-precore-bidi-runner tests

This module provides a BiDiActions interface that wraps the BiDiRunner,
making it compatible with demos migrated from the test suite.
-}
module BiDiActions
  ( BiDiActions (..),
    mkActions,
  )
where

import Data.Aeson (FromJSON, Object, Value)
import Data.Text (Text)
import WebDriverPreCore.BiDi.Protocol
  ( AddDataCollector,
    AddDataCollectorResult,
    AddIntercept,
    AddInterceptResult,
    AddPreloadScript,
    AddPreloadScriptResult,
    Activate,
    AuthRequired,
    BeforeRequestSent,
    BrowsingContext,
    CallFunction,
    CaptureScreenshot,
    CaptureScreenshotResult,
    ClientWindowInfo,
    Close,
    Command (..),
    ContinueRequest,
    ContinueResponse,
    ContinueWithAuth,
    Create,
    CreateUserContext,
    DeleteCookies,
    DeleteCookiesResult,
    Disown,
    DisownData,
    DownloadEnd,
    DownloadWillBegin,
    Evaluate,
    EvaluateResult,
    Event,
    FailRequest,
    FetchError,
    FileDialogOpened,
    GetCookies,
    GetCookiesResult,
    GetData,
    GetDataResult,
    GetRealms,
    GetRealmsResult,
    GetTree,
    GetTreeResult,
    GetUserContextsResult,
    GetClientWindowsResult,
    HandleUserPrompt,
    HistoryUpdated,
    Info,
    JSUInt,
    KnownSubscriptionType (..),
    LocateNodes,
    LocateNodesResult,
    LogEntry,
    Message,
    Navigate,
    NavigateResult,
    OffSpecSubscriptionType,
    NavigationInfo,
    PerformActions,
    Print,
    PrintResult,
    ProvideResponse,
    RealmDestroyed,
    RealmInfo,
    ReleaseActions,
    Reload,
    RemoveDataCollector,
    RemoveIntercept,
    RemovePreloadScript,
    RemoveUserContext,
    ResponseCompleted,
    ResponseStarted,
    SessionNewResult,
    SessionStatusResult,
    SessionSubscibe,
    SessionUnsubscribe,
    SetCacheBehavior,
    SetClientWindowState,
    SetCookie,
    SetCookieResult,
    SetDownloadBehavior,
    SetExtraHeaders,
    SetFiles,
    SetForcedColorsModeThemeOverride,
    SetGeolocationOverride,
    SetLocaleOverride,
    SetNetworkConditions,
    SetScreenOrientationOverride,
    SetScreenSettingsOverride,
    SetScriptingEnabled,
    SetTimezoneOverride,
    SetTouchOverride,
    SetUserAgentOverride,
    SetViewport,
    SessionSubscribeResult (..),
    SubscriptionId (..),
    TraverseHistory,
    UserContext,
    UserPromptClosed,
    UserPromptOpened,
    WebExtensionInstall,
    WebExtensionResult,
    WebExtensionUninstall,
    Capabilities,
  )
import WebDriverPreCore.BiDi.API qualified as API
import WebDriverPreCore.BiDiRunner (BiDiRunner (..))

-- | Extract subscription ID from result
extractSubscription :: SessionSubscribeResult -> SubscriptionId
extractSubscription (MkSessionSubscribeResult {subscription}) = subscription

-- | BiDi actions interface - wraps BiDiRunner with named functions for each command
data BiDiActions = MkBiDiActions
  { -- Session commands
    sessionNew :: Capabilities -> IO SessionNewResult,
    sessionStatus :: IO SessionStatusResult,
    sessionEnd :: IO (),
    sessionSubscribe :: SessionSubscibe -> IO SubscriptionId,
    sessionUnsubscribe :: SessionUnsubscribe -> IO (),
    -- BrowsingContext commands
    browsingContextActivate :: Activate -> IO (),
    browsingContextCaptureScreenshot :: CaptureScreenshot -> IO CaptureScreenshotResult,
    browsingContextClose :: Close -> IO (),
    browsingContextCreate :: Create -> IO BrowsingContext,
    browsingContextGetTree :: GetTree -> IO GetTreeResult,
    browsingContextHandleUserPrompt :: HandleUserPrompt -> IO (),
    browsingContextLocateNodes :: LocateNodes -> IO LocateNodesResult,
    browsingContextNavigate :: Navigate -> IO NavigateResult,
    browsingContextPrint :: Print -> IO PrintResult,
    browsingContextReload :: Reload -> IO (),
    browsingContextSetViewport :: SetViewport -> IO (),
    browsingContextTraverseHistory :: TraverseHistory -> IO (),
    -- Browser commands
    browserClose :: IO (),
    browserCreateUserContext :: CreateUserContext -> IO UserContext,
    browserGetClientWindows :: IO GetClientWindowsResult,
    browserGetUserContexts :: IO GetUserContextsResult,
    browserRemoveUserContext :: RemoveUserContext -> IO (),
    browserSetClientWindowState :: SetClientWindowState -> IO ClientWindowInfo,
    browserSetDownloadBehavior :: SetDownloadBehavior -> IO (),
    -- Emulation commands
    emulationSetForcedColorsModeThemeOverride :: SetForcedColorsModeThemeOverride -> IO (),
    emulationSetGeolocationOverride :: SetGeolocationOverride -> IO (),
    emulationSetLocaleOverride :: SetLocaleOverride -> IO (),
    emulationSetNetworkConditions :: SetNetworkConditions -> IO (),
    emulationSetScreenOrientationOverride :: SetScreenOrientationOverride -> IO (),
    emulationSetScreenSettingsOverride :: SetScreenSettingsOverride -> IO (),
    emulationSetScriptingEnabled :: SetScriptingEnabled -> IO (),
    emulationSetTimezoneOverride :: SetTimezoneOverride -> IO (),
    emulationSetTouchOverride :: SetTouchOverride -> IO (),
    emulationSetUserAgentOverride :: SetUserAgentOverride -> IO (),
    -- Input commands
    inputPerformActions :: PerformActions -> IO (),
    inputReleaseActions :: ReleaseActions -> IO (),
    inputSetFiles :: SetFiles -> IO (),
    -- Network commands
    networkAddDataCollector :: AddDataCollector -> IO AddDataCollectorResult,
    networkAddIntercept :: AddIntercept -> IO AddInterceptResult,
    networkContinueRequest :: ContinueRequest -> IO (),
    networkContinueResponse :: ContinueResponse -> IO (),
    networkContinueWithAuth :: ContinueWithAuth -> IO (),
    networkDisownData :: DisownData -> IO (),
    networkFailRequest :: FailRequest -> IO (),
    networkGetData :: GetData -> IO GetDataResult,
    networkProvideResponse :: ProvideResponse -> IO (),
    networkRemoveDataCollector :: RemoveDataCollector -> IO (),
    networkRemoveIntercept :: RemoveIntercept -> IO (),
    networkSetCacheBehavior :: SetCacheBehavior -> IO (),
    networkSetExtraHeaders :: SetExtraHeaders -> IO (),
    -- Script commands
    scriptAddPreloadScript :: AddPreloadScript -> IO AddPreloadScriptResult,
    scriptCallFunction :: CallFunction -> IO EvaluateResult,
    scriptDisown :: Disown -> IO (),
    scriptEvaluate :: Evaluate -> IO EvaluateResult,
    scriptEvaluateNoWait :: Evaluate -> IO (),
    scriptGetRealms :: GetRealms -> IO GetRealmsResult,
    scriptRemovePreloadScript :: RemovePreloadScript -> IO (),
    -- Storage commands
    storageDeleteCookies :: DeleteCookies -> IO DeleteCookiesResult,
    storageGetCookies :: GetCookies -> IO GetCookiesResult,
    storageSetCookie :: SetCookie -> IO SetCookieResult,
    -- WebExtension commands
    webExtensionInstall :: WebExtensionInstall -> IO WebExtensionResult,
    webExtensionUninstall :: WebExtensionUninstall -> IO (),
    -- Subscription methods
    subscribeMany :: [KnownSubscriptionType] -> (Event -> IO ()) -> IO SubscriptionId,
    subscribeMany' :: [BrowsingContext] -> [UserContext] -> [KnownSubscriptionType] -> (Event -> IO ()) -> IO SubscriptionId,
    -- Log
    subscribeLogEntryAdded :: (LogEntry -> IO ()) -> IO SubscriptionId,
    subscribeLogEntryAdded' :: [BrowsingContext] -> [UserContext] -> (LogEntry -> IO ()) -> IO SubscriptionId,
    -- BrowsingContext
    subscribeBrowsingContextCreated :: (Info -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextCreated' :: [BrowsingContext] -> [UserContext] -> (Info -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDestroyed :: (Info -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDestroyed' :: [BrowsingContext] -> [UserContext] -> (Info -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationStarted :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationStarted' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextFragmentNavigated :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextFragmentNavigated' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextHistoryUpdated :: (HistoryUpdated -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextHistoryUpdated' :: [BrowsingContext] -> [UserContext] -> (HistoryUpdated -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDomContentLoaded :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDomContentLoaded' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextLoad :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextLoad' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDownloadWillBegin :: (DownloadWillBegin -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDownloadWillBegin' :: [BrowsingContext] -> [UserContext] -> (DownloadWillBegin -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDownloadEnd :: (DownloadEnd -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextDownloadEnd' :: [BrowsingContext] -> [UserContext] -> (DownloadEnd -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationAborted :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationAborted' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationCommitted :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationCommitted' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationFailed :: (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextNavigationFailed' :: [BrowsingContext] -> [UserContext] -> (NavigationInfo -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextUserPromptClosed :: (UserPromptClosed -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextUserPromptClosed' :: [BrowsingContext] -> [UserContext] -> (UserPromptClosed -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextUserPromptOpened :: (UserPromptOpened -> IO ()) -> IO SubscriptionId,
    subscribeBrowsingContextUserPromptOpened' :: [BrowsingContext] -> [UserContext] -> (UserPromptOpened -> IO ()) -> IO SubscriptionId,
    -- Network
    subscribeNetworkAuthRequired :: (AuthRequired -> IO ()) -> IO SubscriptionId,
    subscribeNetworkAuthRequired' :: [BrowsingContext] -> [UserContext] -> (AuthRequired -> IO ()) -> IO SubscriptionId,
    subscribeNetworkBeforeRequestSent :: (BeforeRequestSent -> IO ()) -> IO SubscriptionId,
    subscribeNetworkBeforeRequestSent' :: [BrowsingContext] -> [UserContext] -> (BeforeRequestSent -> IO ()) -> IO SubscriptionId,
    subscribeNetworkFetchError :: (FetchError -> IO ()) -> IO SubscriptionId,
    subscribeNetworkFetchError' :: [BrowsingContext] -> [UserContext] -> (FetchError -> IO ()) -> IO SubscriptionId,
    subscribeNetworkResponseCompleted :: (ResponseCompleted -> IO ()) -> IO SubscriptionId,
    subscribeNetworkResponseCompleted' :: [BrowsingContext] -> [UserContext] -> (ResponseCompleted -> IO ()) -> IO SubscriptionId,
    subscribeNetworkResponseStarted :: (ResponseStarted -> IO ()) -> IO SubscriptionId,
    subscribeNetworkResponseStarted' :: [BrowsingContext] -> [UserContext] -> (ResponseStarted -> IO ()) -> IO SubscriptionId,
    -- Script
    subscribeScriptMessage :: (Message -> IO ()) -> IO SubscriptionId,
    subscribeScriptMessage' :: [BrowsingContext] -> [UserContext] -> (Message -> IO ()) -> IO SubscriptionId,
    subscribeScriptRealmCreated :: (RealmInfo -> IO ()) -> IO SubscriptionId,
    subscribeScriptRealmCreated' :: [BrowsingContext] -> [UserContext] -> (RealmInfo -> IO ()) -> IO SubscriptionId,
    subscribeScriptRealmDestroyed :: (RealmDestroyed -> IO ()) -> IO SubscriptionId,
    subscribeScriptRealmDestroyed' :: [BrowsingContext] -> [UserContext] -> (RealmDestroyed -> IO ()) -> IO SubscriptionId,
    -- Input
    subscribeInputFileDialogOpened :: (FileDialogOpened -> IO ()) -> IO SubscriptionId,
    subscribeInputFileDialogOpened' :: [BrowsingContext] -> [UserContext] -> (FileDialogOpened -> IO ()) -> IO SubscriptionId,
    -- Unsubscribe
    unsubscribe :: SubscriptionId -> IO (),
    -- Generic and low-level command methods
    sendCommand :: forall r. (FromJSON r) => Command r -> IO r,
    sendCommand' :: forall r. (FromJSON r) => JSUInt -> Command r -> IO r,
    sendCommandNoWait :: forall r. Command r -> IO (),
    sendOffSpecCommand' :: JSUInt -> Text -> Object -> IO Object,
    sendOffSpecCommandNoWait :: Text -> Object -> IO (),
    -- fallback subscriptions
    subscribeUnknownMany ::
      [OffSpecSubscriptionType] ->
      (Value -> IO ()) ->
      IO SubscriptionId,
    subscribeUnknownMany' ::
      [BrowsingContext] ->
      [UserContext] ->
      [OffSpecSubscriptionType] ->
      (Value -> IO ()) ->
      IO SubscriptionId
  }

-- | Create BiDiActions from a BiDiRunner
mkActions :: BiDiRunner -> BiDiActions
mkActions (MkBiDiRunner {run}) =
  MkBiDiActions
    { -- Session commands
      sessionNew = run . API.sessionNew,
      sessionStatus = run API.sessionStatus,
      sessionEnd = run API.sessionEnd,
      sessionSubscribe = fmap extractSubscription . run . API.sessionSubscribe,
      sessionUnsubscribe = run . API.sessionUnsubscribe,
      -- BrowsingContext commands
      browsingContextActivate = run . API.browsingContextActivate,
      browsingContextCaptureScreenshot = run . API.browsingContextCaptureScreenshot,
      browsingContextClose = run . API.browsingContextClose,
      browsingContextCreate = run . API.browsingContextCreate,
      browsingContextGetTree = run . API.browsingContextGetTree,
      browsingContextHandleUserPrompt = run . API.browsingContextHandleUserPrompt,
      browsingContextLocateNodes = run . API.browsingContextLocateNodes,
      browsingContextNavigate = run . API.browsingContextNavigate,
      browsingContextPrint = run . API.browsingContextPrint,
      browsingContextReload = run . API.browsingContextReload,
      browsingContextSetViewport = run . API.browsingContextSetViewport,
      browsingContextTraverseHistory = run . API.browsingContextTraverseHistory,
      -- Browser commands
      browserClose = run API.browserClose,
      browserCreateUserContext = run . API.browserCreateUserContext,
      browserGetClientWindows = run API.browserGetClientWindows,
      browserGetUserContexts = run API.browserGetUserContexts,
      browserRemoveUserContext = run . API.browserRemoveUserContext,
      browserSetClientWindowState = run . API.browserSetClientWindowState,
      browserSetDownloadBehavior = run . API.browserSetDownloadBehavior,
      -- Emulation commands
      emulationSetForcedColorsModeThemeOverride = run . API.emulationSetForcedColorsModeThemeOverride,
      emulationSetGeolocationOverride = run . API.emulationSetGeolocationOverride,
      emulationSetLocaleOverride = run . API.emulationSetLocaleOverride,
      emulationSetNetworkConditions = run . API.emulationSetNetworkConditions,
      emulationSetScreenOrientationOverride = run . API.emulationSetScreenOrientationOverride,
      emulationSetScreenSettingsOverride = run . API.emulationSetScreenSettingsOverride,
      emulationSetScriptingEnabled = run . API.emulationSetScriptingEnabled,
      emulationSetTimezoneOverride = run . API.emulationSetTimezoneOverride,
      emulationSetTouchOverride = run . API.emulationSetTouchOverride,
      emulationSetUserAgentOverride = run . API.emulationSetUserAgentOverride,
      -- Input commands
      inputPerformActions = run . API.inputPerformActions,
      inputReleaseActions = run . API.inputReleaseActions,
      inputSetFiles = run . API.inputSetFiles,
      -- Network commands
      networkAddDataCollector = run . API.networkAddDataCollector,
      networkAddIntercept = run . API.networkAddIntercept,
      networkContinueRequest = run . API.networkContinueRequest,
      networkContinueResponse = run . API.networkContinueResponse,
      networkContinueWithAuth = run . API.networkContinueWithAuth,
      networkDisownData = run . API.networkDisownData,
      networkFailRequest = run . API.networkFailRequest,
      networkGetData = run . API.networkGetData,
      networkProvideResponse = run . API.networkProvideResponse,
      networkRemoveDataCollector = run . API.networkRemoveDataCollector,
      networkRemoveIntercept = run . API.networkRemoveIntercept,
      networkSetCacheBehavior = run . API.networkSetCacheBehavior,
      networkSetExtraHeaders = run . API.networkSetExtraHeaders,
      -- Script commands
      scriptAddPreloadScript = run . API.scriptAddPreloadScript,
      scriptCallFunction = run . API.scriptCallFunction,
      scriptDisown = run . API.scriptDisown,
      scriptEvaluate = run . API.scriptEvaluate,
      scriptEvaluateNoWait = \cmd -> run (API.scriptEvaluate cmd) >> pure (),
      scriptGetRealms = run . API.scriptGetRealms,
      scriptRemovePreloadScript = run . API.scriptRemovePreloadScript,
      -- Storage commands
      storageDeleteCookies = run . API.storageDeleteCookies,
      storageGetCookies = run . API.storageGetCookies,
      storageSetCookie = run . API.storageSetCookie,
      -- WebExtension commands
      webExtensionInstall = run . API.webExtensionInstall,
      webExtensionUninstall = run . API.webExtensionUninstall,
      -- Subscription methods - Note: These require event handling which is not yet implemented in BiDiRunner
      subscribeMany = \_ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeMany' = \_ _ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeLogEntryAdded = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeLogEntryAdded' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextCreated = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextCreated' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDestroyed = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDestroyed' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationStarted = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationStarted' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextFragmentNavigated = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextFragmentNavigated' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextHistoryUpdated = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextHistoryUpdated' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDomContentLoaded = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDomContentLoaded' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextLoad = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextLoad' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDownloadWillBegin = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDownloadWillBegin' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDownloadEnd = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextDownloadEnd' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationAborted = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationAborted' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationCommitted = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationCommitted' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationFailed = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextNavigationFailed' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextUserPromptClosed = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextUserPromptClosed' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextUserPromptOpened = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeBrowsingContextUserPromptOpened' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkAuthRequired = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkAuthRequired' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkBeforeRequestSent = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkBeforeRequestSent' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkFetchError = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkFetchError' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkResponseCompleted = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkResponseCompleted' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkResponseStarted = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeNetworkResponseStarted' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeScriptMessage = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeScriptMessage' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeScriptRealmCreated = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeScriptRealmCreated' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeScriptRealmDestroyed = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeScriptRealmDestroyed' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeInputFileDialogOpened = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeInputFileDialogOpened' = \_ _ _ -> error "Subscription support not yet implemented in BiDiRunner",
      unsubscribe = \_ -> error "Subscription support not yet implemented in BiDiRunner",
      -- Generic and low-level command methods
      sendCommand = run,
      sendCommand' = \_ cmd -> run cmd, -- JSUInt ID is ignored in current BiDiRunner
      sendCommandNoWait = \_ -> pure (), -- Ignore the command result for NoWait version
      sendOffSpecCommand' = \_ _ _ -> error "Off-spec command support not yet implemented in BiDiRunner",
      sendOffSpecCommandNoWait = \_ _ -> error "Off-spec command support not yet implemented in BiDiRunner",
      subscribeUnknownMany = \_ _ -> error "Subscription support not yet implemented in BiDiRunner",
      subscribeUnknownMany' = \_ _ _ _ -> error "Subscription support not yet implemented in BiDiRunner"
    }
